title: Klára Pitlachová
email: karelsuchomel@windowslive.com
description: >-
  Doprovázení, poradenství, terapie - pomoc při překonávání nejasného úseku vaší životní cesty.
keywords: Psycholožka, psycholog, soukromá psychologická praxe, psycholog Brno, doprovázení, poradenství, terapie
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://klarapitlachova.cz" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache

prose:
  siteurl: 'https://klarapitlachova.cz'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets/files/'
  ignore:
    - _config.yml
    - Gemfile.lock
    - Gemfile
    - CNAME
    - 404.html
    - .gitignore
    - /assets
    - /_site
    - /_layouts
    - /_includes
    - /_sass
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    jak-pracuji.md:
      - name: "layout"
        field:
          element: "hidden"
          value: "how-i-work-page"
      - name: "title"
        field:
          element: "text"
          label: "Nadpis"
      - name: "FirstHeadilne"
        field:
          element: "text"
          label: "První blok - nadpis"
      - name: "FirstTextBoxLeft"
        field:
          element: "text"
          label: "První blok - sloupec nalevo"
      - name: "FirstTextBoxRight"
        field:
          element: "text"
          label: "První blok - sloupec napravo"
      - name: "SecondHeadilne"
        field:
          element: "text"
          label: "Druhý blok - nadpis"
      - name: "SecondTextBoxLeft"
        field:
          element: "text"
          label: "Druhý blok - sloupec nalevo"
      - name: "SecondTextBoxRight"
        field:
          element: "text"
          label: "Druhý blok - sloupec napravo"